version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: meadow
      MONGO_INITDB_ROOT_PASSWORD: meadow_su
    volumes:
      - ./database/data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: warm_milk
      ME_CONFIG_BASICAUTH_PASSWORD: warm_milk_su
      ME_CONFIG_MONGODB_URL: mongodb://meadow:meadow_su@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_AUTH_ENABLED: "true"
